version: '3'
services:
  ubuntu_container:
    image: ubuntu:latest
    command: sleep infinity

  postgres_container:
    image: postgres:latest
    command: sleep infinity   
    ports:
      - "5432:5432"
    depends_on:
      - ubuntu_container

  python_container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - ubuntu_container
      - postgres_container

  



