version: '3'
services:
  ubuntu_container:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    volumes:
      - .:/webapp  
    ports:
      - "8000:8000"
    command: sleep infinity     

  # postgres_container:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.postgres
  #   command: sleep infinity   
  #   ports:
  #     - "5432:5432"
  #   depends_on:
  #     - ubuntu_container





