version: '3'
services:
  #ubuntu_container:
  #  image: ubuntu:latest
  #  command: sleep infinity

  python_container:
    image: python:latest
    command: sleep infinity
    ports:
      - "8000:8000"

  postgres_container:
    image: postgres:latest
    command: sleep infinity   
    ports:
      - "5432:5432"



