# Generated by Django 4.2.4 on 2023-09-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_capturedpicture_image_weighthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighthistory',
            name='timestamp',
        ),
    ]
